### ISSUE TITLE
Refactoring checklist

### ISSUE THREAD

**Issue by ssemenkoff** [xmla-services/org.eclipse.daanse.xmla.client.typescript#763]
- [ ] Multilevel dashboard
  - [ ] Move movable logic to `useMovableLayout` composable.
  
- [ ] Widgets
  - [ ] Move Store-related logic to `useStore` composable
  - [ ] Move serialization/deserialization logic to `useSerialization`
  
- [ ] Stores
  - [ ] Strong typing on `XMLAStore.ts`
  - [ ] Strong typing on `Store.ts`
  - [ ] Strong typing on datasources
  
- [ ] Rework the way settings are set in the application
  - [ ] Propper interfaces for settings for each widget
  - [ ] `useSettings` composable to handle settings logic
  
- [ ] MDX Generator
   - [ ] Strong typing
   - [ ] Check if generator can be used as separate module
